const { application } = require('express')
const express = require('express')
const adminRoute = express()
const adminController = require("../controller/adminController")
const fileUpload = require('../middleware/multer')

adminRoute.get("/",adminController.dashboard)
adminRoute.get("/adminlogin",adminController.adminLogin)
adminRoute.post("/adminlogged",adminController.adminLogged)
adminRoute.get("/adminuserdata",adminController.adminUserData)
adminRoute.get("/blockuser/:id",adminController.UserBlock)
adminRoute.get("/unblockuser/:id",adminController.userUnBlock) 
adminRoute.get("/category",adminController.adminCategory)
adminRoute.get("/newcategory",adminController.newCategory)
adminRoute.post("/addcategory", adminController.addcategory)
adminRoute.get("/editcategory",adminController.editCategory)
adminRoute.post("/updatecategory/:id",adminController.updateCategory)
adminRoute.delete("/deletecategory",adminController.deleteCategory)
adminRoute.post('/addproduct',adminController.addproduct)
adminRoute.get("/productmgt",adminController.productManagement)
adminRoute.get('/add-product',adminController.addGetProduct)
adminRoute.get('/listing/:id',adminController.listingProd)
adminRoute.get('/unlisting/:id',adminController.unlistingProd)
adminRoute.get("/producteditpage",adminController.prodEdit)
adminRoute.post("/editproduct", adminController.productEdit)
adminRoute.get("/coupon",adminController.couponPage)
adminRoute.get("/addcouponpage",adminController.addCouponPage)
adminRoute.post("/addcoupon",adminController.addCoupon)
adminRoute.get("/couponeditpage/:id",adminController.couponEditPage)
adminRoute.post("/couponedit",adminController.couponEdit)
adminRoute.get("/ordermanagementpage",adminController.orderManagmentPage)
adminRoute.get("/cancelOrder",adminController.cancelOrder)
adminRoute.post("/orderStatus",adminController.changeOrderStatus)
adminRoute.get("/report",adminController.report)

// adminRoute.get("/graph",adminController.graph)  

module.exports = adminRoute