const { application } = require('express')
const express = require('express')
const { UserChannelPage } = require('twilio/dist/lib/rest/chat/v1/service/user/userChannel')
const userRoute = express()
const userController = require("../controller/usercontroller")

//get
userRoute.get("/home",userController.userHome)
userRoute.get("/otpfail",userController.otpFail)
userRoute.get("/resendotp",userController.resendOtp)
userRoute.get("/login",userController.userLogin)
userRoute.get("/signup",userController.userSignup)
userRoute.get("/otp",userController.userOtp)
userRoute.post("/otpverification",userController.otpVerification)
userRoute.get("/signout",userController.signOut)
userRoute.get("/shop",userController.shop)
userRoute.get("/cart",userController.cartPage)
userRoute.get("/wishlistpage",userController.wishListPage)
userRoute.get("/profilepage",userController.profilePage)
userRoute.get("/singleproduct",userController.viewProduct)
userRoute.get("/addresspage",userController.addAddressPage)
userRoute.get("/deleteaddress",userController.addressDelete)
userRoute.get("/editaddresspage",userController.editAddressPage)
userRoute.get("/checkoutpage",userController.checkoutPage)
userRoute.get("/confirmorderpage",userController.confirmOrderPage)
userRoute.get("/usermgtpage",userController.orderManagementPage)
//post
userRoute.post("/logged",userController.loggedIn)
userRoute.post("/addtocart",userController.addToCart)
userRoute.post("/changequantity",userController.changeQuantity)
userRoute.post("/addToWishlist",userController.addToWishlist)
userRoute.post("/updateProfile",userController.editUserDetails)
userRoute.post("/addaddress",userController.addAddress)
userRoute.post("/addaddressprofile", userController.addAddressProfile)
userRoute.post("/addressEdit",userController.editAddress)
userRoute.post("/applycoupon",userController.checkCoupon)
userRoute.post("/createAccount",userController.doRegister)
userRoute.post("/confirmorder",userController.confirmOrder)
userRoute.post('/verifyPayement', userController.verifyPayement)
//others
userRoute.patch("/cancelorder",userController.cancelOrder)


module.exports = userRoute
